# Generated by Django 5.1.1 on 2024-09-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(max_length=255)),
                ('destinatario', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
